name: Cypress Tests

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  cypress-tests:
    name: Run Cypress Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, edge]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Install Cypress
        run: npx cypress install

      - name: Create Reports Directory
        run: |
          mkdir -p cypress/reports/mochawesome-report
          mkdir -p cypress/reports/.jsons

      - name: Grant Permissions
        run: chmod +x ./node_modules/.bin/cypress

      - name: Run Cypress Tests on ${{ matrix.browser }}
        run: |
          BRANCH_NAME=""
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BRANCH_NAME="${{ github.base_ref }}"
          else
            BRANCH_NAME="${{ github.ref_name }}"
          fi

          if [ "$BRANCH_NAME" = "staging" ]; then
            echo "Running smoke tests on staging branch..."
            npx cypress run \
              --browser ${{ matrix.browser }} \
              --env grep=@smoke \
              --reporter cypress-mochawesome-reporter \
              --reporter-options charts=true,reportDir=cypress/reports/mochawesome-report,overwrite=false,html=true,json=true,embeddedScreenshots=true
          elif [ "$BRANCH_NAME" = "main" ]; then
            echo "Running full test suite on main branch..."
            npx cypress run \
              --browser ${{ matrix.browser }} \
              --reporter cypress-mochawesome-reporter \
              --reporter-options charts=true,reportDir=cypress/reports/mochawesome-report,overwrite=false,html=true,json=true,embeddedScreenshots=true
          else
            echo "Branch $BRANCH_NAME not configured for testing"
            exit 1
          fi

      - name: Generate Mochawesome Report
        if: always()
        run: |
          npx mochawesome-merge cypress/reports/mochawesome-report/*.json > cypress/reports/mochawesome-report/output.json
          npx marge cypress/reports/mochawesome-report/output.json --reportDir cypress/reports/mochawesome-report --inline

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.browser }}-${{ github.sha }}
          path: |
            cypress/reports/mochawesome-report
            cypress/screenshots
            cypress/videos
          retention-days: 30

      - name: Upload Test Results on Failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-failures-${{ matrix.browser }}-${{ github.sha }}
          path: |
            cypress/screenshots
            cypress/videos
          retention-days: 7