name: Cypress Tests

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  cypress-tests:
    name: Run Cypress Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, edge, firefox]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Install Cypress
        run: npx cypress install

      - name: Grant Permissions
        run: chmod +x ./node_modules/.bin/cypress

      - name: Run Cypress Tests on ${{ matrix.browser }}
        run: |
          BRANCH_NAME=""
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BRANCH_NAME="${{ github.base_ref }}"
          else
            BRANCH_NAME="${{ github.ref_name }}"
          fi

          if [ "$BRANCH_NAME" = "staging" ]; then
            echo "Running smoke tests on staging branch..."
            npx cypress run \
              --browser ${{ matrix.browser }} \
              --env grep=@smoke \
              --reporter mochawesome \
              --reporter-options reportDir=cypress/reports,reportFilename=index.html
          elif [ "$BRANCH_NAME" = "main" ]; then
            echo "Running full test suite on main branch..."
            npx cypress run \
              --browser ${{ matrix.browser }} \
              --reporter mochawesome \
              --reporter-options reportDir=cypress/reports,reportFilename=index.html
          else
            echo "Branch $BRANCH_NAME not configured for testing"
            exit 1
          fi

      - name: Archive Mochawesome Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-report-${{ matrix.browser }}-${{ github.sha }}
          path: cypress/reports/